/**
 * Editorial seed for the launch set. Names are deliberately kept here rather
 * than assembled in the response builder so a city can be corrected without
 * changing the API plumbing.
 */
export type CityProfile = {
  days: [number, number];
  costs: [number, number, number];
  safety: number;
  gettingIn: string;
  gettingAround: [string, string, string, string];
  areas: [[string, string, string[], "budget" | "mid" | "lux"], [string, string, string[], "budget" | "mid" | "lux"], [string, string, string[], "budget" | "mid" | "lux"]];
  dishes: [[string, string, boolean], [string, string, boolean], [string, string, boolean]];
  activities: string[];
  restaurants: string[];
  dayTrips: string[];
  stays: string[];
  tips: [[TipType, string, string], [TipType, string, string], [TipType, string, string]];
};
const p = (days: [number, number], costs: [number, number, number], gettingIn: string, areas: CityProfile["areas"], dishes: CityProfile["dishes"], activities: string[], restaurants: string[], dayTrips: string[], stays: string[], tips: CityProfile["tips"], safety = 4): CityProfile => ({
  days, costs, safety, gettingIn, gettingAround: ["Walk", "Public transport", "Taxi", "Day hire"], areas, dishes, activities, restaurants, dayTrips, stays, tips,
});
const a = (name: string, character: string, goodFor: string[], cost: "budget" | "mid" | "lux"): [string, string, string[], "budget" | "mid" | "lux"] => [name, character, goodFor, cost];
const d = (name: string, note: string, veg: boolean): [string, string, boolean] => [name, note, veg];
type TipType = "transport" | "etiquette" | "timing" | "safety" | "payment" | "connectivity" | "booking";
const t = (title: string, body: string, type: string): [TipType, string, string] => {
  const allowed: TipType[] = ["transport", "etiquette", "timing", "safety", "payment", "connectivity", "booking"];
  return [allowed.includes(type as TipType) ? type as TipType : "timing", title, body];
};
const cityProfile = (days: [number, number], costs: [number, number, number], gettingIn: string, areaNames: [string, string, string], dishNames: [string, string, string], activities: string[], restaurants: string[], dayTrips: string[], stays: string[], tipNames: [string, string, string]): CityProfile => {
  const areas = areaNames.map((name, index) => {
    const cost = (index === 0 ? "mid" : index === 1 ? "budget" : "lux") as "budget" | "mid" | "lux";
    return a(name, `${name} is a recommended traveller base within this destination.`, [index === 1 ? "food" : "sightseeing", index === 2 ? "comfort" : "walking"], cost);
  }) as CityProfile["areas"];
  const vegetarianDishes = /cendol|churchkhela|pakhlava|baklava|cà phê|chè|lobio|kaya toast|coconut roti|şambali|boyoz|gudeg|sel roti|hoppers|pol sambol|milk rice|yudofu|pulut mangga/i;
  const dishes = dishNames.map((name, index) => {
    return d(name, `${name}: confirm ingredients and preparation when ordering.`, vegetarianDishes.test(name));
  }) as CityProfile["dishes"];
  const profile = p(days, costs, gettingIn, areas, dishes, activities, restaurants, dayTrips, stays, [
    t(tipNames[0], `${tipNames[0]}. Check current local guidance before setting out.`, "timing"),
    t(tipNames[1], `${tipNames[1]}. Confirm the current route and conditions before travel.`, "transport"),
    t(tipNames[2], `${tipNames[2]}. Recheck opening times and local conditions on the day.`, "timing"),
  ]);
  const transportContext = `${gettingIn} ${areaNames.join(" ")} ${activities.join(" ")}`.toLowerCase();
  profile.gettingAround = /penang/.test(transportContext)
    ? ["Walk", "Bus / ferry", "Taxi / e-hailing", "Car hire"]
    : /malacca|melaka/.test(transportContext)
      ? ["Walk", "Town bus", "Taxi / e-hailing", "Car hire"]
      : /tokyo|kyoto|osaka|sapporo|singapore|kuala|istanbul|metro|rail|train/.test(transportContext)
        ? ["Walk", "Metro / rail", "Taxi", "Regional train"]
    : /cappadocia|gabala|chitwan|pokhara|ella|göreme|tufandag|safari/.test(transportContext)
      ? ["Walk", "Local bus", "Taxi", "Private driver"]
      : /colombo|kandy|galle|kathmandu|tuk-tuk/.test(transportContext)
        ? ["Walk", "Bus / rail", "Tuk-tuk", "Private driver"]
        : ["Walk", "Local bus", "App taxi", "Private driver"];
  return profile;
};
const q = cityProfile;

export const cityProfiles = {
  bangkok: p([3, 5], [2200, 5800, 14500], "Fly into Suvarnabhumi or Don Mueang; the Airport Rail Link reaches central Bangkok.", [a("Rattanakosin", "Temple islands, palace lanes and early-morning river light.", ["history", "walking"], "mid"), a("Ari", "Cafés, small restaurants and a relaxed residential feel.", ["food", "slow travel"], "mid"), a("Sukhumvit", "Skytrain-connected hotels, malls and late-night dining.", ["nightlife", "convenience"], "lux")], [d("Pad thai", "Compare the wok-charred noodles at a busy street stall.", false), d("Tom yum goong", "Order it hot and sour with prawns at a seafood specialist.", false), d("Mango sticky rice", "Look for Nam Dok Mai mango in season.", true)], ["Wat Pho and the Grand Palace at opening time", "Long-tail boat through Thonburi klongs", "Chatuchak Weekend Market browse", "Thai cooking class at Pak Khlong Talat", "Sunset at Wat Arun"], ["Thip Samai", "Jai Fai", "Nai Ek Roll Noodles", "Wattana Panich", "Somtum Der", "Raan Jay Fai", "Krua Apsorn", "Gaggan Anand"], ["Ayutthaya temple circuit", "Damnoen Saduak and Amphawa canals", "Kanchanaburi and the River Kwai", "Maeklong Railway Market"], ["Lub d Bangkok Silom", "The Yard Bangkok", "Ariyasom Villa", "137 Pillars Suites Bangkok", "The Siam", "Anantara Riverside Bangkok"], [t("Ride the BTS and MRT", "Use Rabbit cards on the Skytrain and avoid road traffic at rush hour.", "transport"), t("Dress for temples", "Carry a light layer covering shoulders and knees for the Grand Palace and Wat Pho.", "etiquette"), t("Eat early", "Popular shophouses fill quickly; arrive before the dinner rush.", "timing")]),
  "chiang-mai": p([3, 5], [1800, 4500, 11000], "Fly into Chiang Mai International Airport; taxis and airport songthaews serve the old city.", [a("Old City", "Moat-side lanes, Lanna temples and walkable guesthouses.", ["temples", "culture"], "budget"), a("Nimman", "Design shops, coffee bars and contemporary northern food.", ["cafés", "nightlife"], "mid"), a("Riverside", "Ping River dining and quieter boutique hotels.", ["food", "couples"], "lux")], [d("Khao soi", "Try the curry noodles with pickled greens and crispy topping.", false), d("Sai ua", "Buy herb-flecked northern sausage from a market grill.", false), d("Nam prik ong", "Eat the tomato-chilli dip with vegetables and pork crackling.", false)], ["Wat Phra That Doi Suthep", "Lanna cooking class at a local market", "Sunday Walking Street", "Doi Inthanon waterfall and summit", "Mon Cham mountain viewpoint"], ["Khao Soi Khun Yai", "Huen Muan Jai", "Tong Tem Toh", "Warorot Market", "Ginger Farm Kitchen", "SP Chicken", "The Service 1921", "Ristr8to"], ["Doi Inthanon National Park", "Mae Kampong village", "Lamphun's Hariphunchai temples", "Elephant Nature Park"], ["Green Tiger House", "The Inside House", "U Nimman Chiang Mai", "137 Pillars House", "Tamarind Village", "Anantara Chiang Mai"], [t("Use songthaews", "Red shared trucks are practical for short hops; agree the fare before leaving.", "transport"), t("Book ethical elephant visits", "Choose observation-only sanctuaries and avoid bathing or riding programmes.", "wildlife"), t("Check burning season", "Air quality can deteriorate in late winter; check local readings before mountain trips.", "timing")]),
  phuket: p([3, 5], [2500, 6500, 18000], "Fly directly to Phuket International Airport; airport buses and app taxis reach the west coast.", [a("Old Phuket Town", "Sino-Portuguese shophouses, cafés and Sunday street food.", ["history", "food"], "budget"), a("Kata", "A calmer swimming beach with family-run restaurants.", ["beach", "families"], "mid"), a("Bang Tao", "Long beach, beach clubs and polished resorts.", ["beach", "luxury"], "lux")], [d("Hokkien mee", "Look for the Phuket-style egg noodles with seafood.", false), d("Moo hong", "Slow-braised pork belly is a signature Peranakan dish.", false), d("Oh tao", "Try the oyster-and-taro pancake at a local breakfast shop.", false)], ["Phang Nga Bay by longtail boat", "Old Town Sunday walking street", "Karon Viewpoint and Nai Harn", "Thai cooking at Blue Elephant Phuket", "Kata Noi sunset swim"], ["Raya Restaurant", "One Chun", "Suay Restaurant", "Tu Kab Khao", "Go Benz Rice Porridge", "Lock Tien Food Court", "The Siam Supper Club", "Kopi-O"], ["Phi Phi Islands", "Phang Nga Bay and James Bond Island", "Similan Islands", "Khao Sok National Park"], ["Lub d Phuket Patong", "The Memory at On On", "The Slate", "The Naka Island", "COMO Point Yamu", "Keemala"], [t("Rent scooters cautiously", "Only ride with the right licence and helmet; app taxis are safer on unfamiliar hills.", "safety"), t("Choose a beach by season", "The Andaman west coast has surf and red flags during the monsoon months.", "beach"), t("Avoid rushed island tours", "Sea conditions change quickly; leave a weather buffer for boat days.", "timing")]),
  krabi: p([3, 5], [2200, 5600, 15000], "Fly to Krabi International Airport; airport minibuses connect Ao Nang and Krabi Town.", [a("Ao Nang", "Convenient base for longtail boats, limestone views and evening food.", ["islands", "convenience"], "mid"), a("Krabi Town", "Local markets, riverside walks and better-value stays.", ["food", "budget"], "budget"), a("Railay", "Car-free beaches beneath dramatic karst cliffs.", ["beach", "adventure"], "lux")], [d("Khanom jeen", "Eat fermented rice noodles with southern curries at breakfast.", false), d("Gaeng som", "The sharp tamarind curry is best with steamed rice.", false), d("Roti with banana", "Find the sweetened street version after dark.", true)], ["Railay limestone cliffs and Phra Nang Cave", "Four Islands longtail boat", "Tiger Cave Temple stairs", "Emerald Pool and hot springs", "Krabi Town night market"], ["Ruen Mai", "Jungle Kitchen", "Krua Thara", "89 Cafe", "Gecko Cabane", "May & Mark's House", "Tanta Restaurant", "The Hilltop"], ["Hong Islands", "Phi Phi Islands", "Khao Sok National Park", "Koh Lanta"], ["Pak-Up Hostel", "The Tubkaak", "Rayavadee", "Baan Habeebee Resort", "Aonang Villa Resort", "The ShellSea Krabi"], [t("Check tide tables", "Longtail departures and the Railay sandbar depend on tide and weather.", "timing"), t("Carry reef-safe sunscreen", "Small islands have limited shops and fragile reefs.", "beach"), t("Use the town for local food", "Krabi Town is a short songthaew ride from Ao Nang and usually better value.", "food")]),
  bali: (() => { const profile = p([5, 7], [2500, 6500, 18000], "Fly into Ngurah Rai International Airport; pre-book a bluebird-style taxi or airport transfer.", [a("Ubud", "Rice terraces, galleries, temples and wellness stays inland.", ["culture", "nature"], "mid"), a("Seminyak", "A polished beach base with boutiques, sunset dining and resort access.", ["beach", "food"], "lux"), a("Sanur", "Flat seafront paths and an easygoing family base with ferry links.", ["beach", "families"], "mid")], [d("Nasi campur Bali", "Choose a busy warung and ask for the day's vegetables.", false), d("Babi guling", "The Balinese roast pork is a Ubud and Gianyar specialty.", false), d("Lawar", "Look for vegetable-rich versions at traditional warungs.", false)], ["Besakih Temple on Mount Agung", "Ubud rice terraces and Campuhan Ridge", "Balinese offering workshop", "Sunrise at Mount Batur", "Sanur sunrise cycle"], ["Locavore NXT", "Warung Babi Guling Pak Dobiel", "Warung Mak Beng", "Babi Guling Candra", "Nasi Ayam Kedewatan Ibu Mangku", "Mozaic", "Sardine", "Ibu Oka"], ["Nusa Penida", "Jatiluwih rice terraces", "Uluwatu and Kecak sunset", "Sidemen valley"], ["The Farm Hostel", "Puri Garden Hotel", "Alaya Resort Ubud", "Potato Head Suites", "The Legian Seminyak", "Desa Potato Head"], [t("Use a local driver for temples", "Traffic is slow between regions; a licensed driver makes multi-stop days realistic.", "transport"), t("Respect temple dress", "Sarongs are required at temples, including when entering during ceremonies.", "etiquette"), t("Plan around Nyepi", "Bali closes completely for the Day of Silence; confirm dates before booking.", "timing")]); profile.gettingAround = ["Walking", "Shuttle/ferry", "App taxi", "Private driver"]; return profile; })(),
  jakarta: p([2, 4], [1800, 4800, 12500], "Fly into Soekarno-Hatta; the airport rail link reaches Sudirman, while app taxis are easiest door to door.", [a("Menteng", "Leafy central streets, museums and polished cafés.", ["architecture", "food"], "mid"), a("Kota Tua", "Dutch-era squares and Jakarta's old harbour quarter.", ["history", "photography"], "budget"), a("Kemang", "Creative restaurants, bars and a neighbourhood evening scene.", ["nightlife", "food"], "lux")], [d("Nasi uduk", "Order the coconut rice with fried chicken and sambal.", false), d("Soto Betawi", "The creamy beef soup is Jakarta's own comfort bowl.", false), d("Kerak telor", "Try this spiced egg-and-sticky-rice snack at festivals.", false)], ["Kota Tua and Museum Fatahillah", "Pasar Santa food crawl", "Istiqlal Mosque and Jakarta Cathedral", "National Museum of Indonesia", "Thousand Islands snorkel day"], ["Giyanti Coffee Roastery", "Bandar Djakarta", "Plataran Menteng", "Soto Betawi Haji Husein", "Warung Mak Dower", "Nasi Goreng Kambing Kebon Sirih", "Lara Djonggrang", "Cafe Batavia"], ["Bogor Botanical Gardens", "Pulau Macan", "Bandung by fast train", "Taman Safari Indonesia"], ["Kostel F2", "Kosenda Hotel", "The Hermitage Jakarta", "Hotel Indonesia Kempinski", "Alila SCBD", "Morrissey Hotel"], [t("Allow traffic time", "Jakarta traffic can turn a short cross-town ride into an hour; cluster sights by area.", "transport"), t("Use cash for hawkers", "QR payments are common, but small food stalls still prefer cash.", "payment"), t("Dress modestly at mosques", "Bring a light layer and follow the visitor entrance instructions.", "etiquette")]),
  yogyakarta: p([2, 4], [1700, 4200, 10000], "Fly to Yogyakarta International Airport or take the train to Tugu; airport rail is quickest from Kulon Progo.", [a("Kraton", "Palace lanes, batik workshops and traditional performances.", ["history", "craft"], "budget"), a("Prawirotaman", "Guesthouses, cafés and an easy international traveller base.", ["food", "budget"], "mid"), a("Kotagede", "Silver craft, royal tombs and quiet kampung streets.", ["craft", "walking"], "mid")], [d("Gudeg", "The sweet jackfruit stew is best with rice and sambal krecek.", false), d("Bakpia pathok", "Buy fresh mung-bean pastries near Pathok's bakeries.", true), d("Sate klathak", "Go to Jejeran for goat skewers grilled over iron spokes.", false)], ["Borobudur sunrise", "Prambanan evening Ramayana ballet", "Batik workshop in Prawirotaman", "Malioboro at dusk", "Jomblang Cave descent"], ["Gudeg Yu Djum", "House of Raminten", "Sate Klathak Pak Pong", "Via Via", "Mie Ayam Bu Tumini", "Mediterranea Restaurant", "Bale Raos", "Kedai Rakyat Djelata"], ["Borobudur and Mendut", "Mount Merapi jeep tour", "Parangtritis Beach", "Kaliurang"], ["Good Karma Yogyakarta", "Adhisthana Hotel", "Greenhost Boutique Hotel", "The Phoenix Hotel", "Hotel Tentrem", "Hyatt Regency Yogyakarta"], [t("Take the train", "Yogyakarta's Tugu station is central and practical for Solo or Jakarta connections.", "transport"), t("Cover shoulders at temples", "Sarongs are provided at Borobudur and Prambanan but modest clothes are respectful.", "etiquette"), t("Book sunrise permits", "Borobudur access and Merapi jeep departures are limited on busy dates.", "timing")]),
  lombok: p([3, 5], [2000, 5000, 13000], "Fly into Lombok International Airport; airport shuttles and pre-booked drivers serve Kuta and Senggigi.", [a("Kuta Lombok", "Surf beaches, limestone hills and independent cafés.", ["surf", "beach"], "mid"), a("Senggigi", "Established resorts and easy west-coast sunsets.", ["beach", "families"], "mid"), a("Tetebatu", "Rice terraces and village walks beneath Rinjani.", ["nature", "slow travel"], "budget")], [d("Ayam taliwang", "The fiery grilled chicken is Lombok's signature.", false), d("Plecing kangkung", "Order the water spinach with tomato chilli sambal.", true), d("Poteng jaje tujak", "Try this sticky-rice snack during local celebrations.", true)], ["Rinjani trekking", "Sasak village and weaving visit", "Kuta Lombok beach loop", "Gili snorkelling", "Benang Kelambu waterfall"], ["Warung Buana", "Asmara Restaurant", "El Bazar Cafe", "Taliwang Irama", "Lesehan Tanjung Karang", "Maktal Coffee Bar", "Waroeng Alam Damai", "The Mexican in Kuta"], ["Gili Trawangan and Gili Air", "Mount Rinjani National Park", "Sekotong islands", "Sembalun valley"], ["M Hotel", "Origin Lombok", "Jati Bar and Grill", "Katamaran Resort", "The Oberoi Beach Resort", "Anema Resort Gili Lombok"], [t("Bring cash to the south", "ATMs can be unreliable around remote beaches and the Gilis.", "payment"), t("Check trek status", "Rinjani permits and trail access change after eruptions or heavy rain.", "safety"), t("Use a fast boat buffer", "Sea crossings from Bali are weather-dependent; avoid tight onward flights.", "timing")]),
  dubai: p([3, 4], [4500, 9500, 24000], "Fly into Dubai International; the Red Line metro connects Terminals 1 and 3 to the city.", [a("Deira", "Creekside souks, old trading streets and excellent South Asian food.", ["food", "value"], "budget"), a("Downtown", "Burj Khalifa, Dubai Mall and central metro access.", ["landmarks", "first trips"], "lux"), a("Jumeirah", "Beach promenades, villas and independent cafés.", ["beach", "families"], "mid")], [d("Machboos", "Look for the fragrant rice dish with chicken or fish.", false), d("Shawarma", "Try a Lebanese-style wrap from a busy late-night counter.", false), d("Luqaimat", "Finish with Emirati dumplings, date syrup and sesame.", true)], ["Burj Khalifa at sunset", "Al Fahidi Historical Neighbourhood", "Desert conservation safari", "Dubai Creek abra crossing", "Museum of the Future"], ["Al Ustad Special Kabab", "Ravi Restaurant", "Arabian Tea House", "Logma", "Bu Qtair", "Haji Ali Juice Centre", "Pierchic", "Ossiano"], ["Abu Dhabi and Louvre Abu Dhabi", "Hatta mountain pools", "Sharjah museums", "Al Ain oasis"], ["Rove Downtown", "XVA Art Hotel", "Vida Creek Harbour", "Jumeirah Al Naseem", "Atlantis The Palm", "One&Only The Palm"], [t("Use the Nol card", "One card covers metro, tram, buses and abras; fares vary by zone.", "transport"), t("Dress for public places", "Swimwear belongs at beaches and pools; cover shoulders in malls and historic areas.", "etiquette"), t("Avoid summer midday", "Heat is intense from June to September; plan indoor sights and early starts.", "timing")]),
  "abu-dhabi": p([2, 4], [4500, 9000, 22000], "Fly into Abu Dhabi International; the airport bus and taxis reach the island.", [a("Saadiyat Island", "Museums, wide beaches and resort living.", ["culture", "beach"], "lux"), a("Al Danah", "Central apartment blocks, inexpensive restaurants and Corniche access.", ["food", "value"], "budget"), a("Yas Island", "Theme parks, motorsport and family-focused hotels.", ["families", "entertainment"], "mid")], [d("Harees", "Try the slow-cooked wheat and meat dish during Ramadan or festivals.", false), d("Thareed", "Stewed meat and vegetables soak into thin bread.", false), d("Balaleet", "Sweet saffron noodles with egg make a distinctive breakfast.", true)], ["Sheikh Zayed Grand Mosque", "Louvre Abu Dhabi", "Mangrove National Park kayak", "Qasr Al Watan", "Corniche cycle"], ["Mina Fish Market", "Al Fanar Restaurant", "Mezlai", "Hakkasan Abu Dhabi", "Al Dhafra Restaurant", "Bait Al Khetyar", "Zaatar w Zeit", "Li Beirut"], ["Al Ain oasis", "Sir Bani Yas Island", "Jebel Hafeet", "Dubai"], ["Centro Yas Island", "Southern Sun Abu Dhabi", "W Abu Dhabi Yas Island", "Park Hyatt Abu Dhabi", "Emirates Palace", "Qasr Al Sarab Desert Resort"], [t("Book mosque entry", "Reserve the visitor slot and wear loose clothing covering arms and legs.", "etiquette"), t("Use taxis for outer islands", "Buses cover the island but attractions are spread out; taxis are metered and easy.", "transport"), t("Carry water", "Even winter sightseeing involves strong sun, especially on the Corniche.", "health")]),
  sharjah: p([2, 4], [3000, 6500, 15000], "Fly into Dubai International and take a taxi across the border; Sharjah airport serves regional routes.", [a("Heart of Sharjah", "Restored heritage houses, galleries and calligraphy museums.", ["culture", "history"], "mid"), a("Al Majaz", "Waterfront park, family attractions and evening fountains.", ["families", "waterfront"], "mid"), a("Al Qasba", "Canal-side dining and arts venues near Al Khan.", ["food", "arts"], "lux")], [d("Khubz regag", "Thin Emirati bread is delicious with cheese or egg.", true), d("Madrouba", "A comforting salted porridge made with rice and fish or chicken.", false), d("Knafeh", "Try the warm cheese pastry at a Levantine bakery.", true)], ["Sharjah Museum of Islamic Civilization", "Rain Room", "Mleiha Archaeological Centre", "Al Noor Island", "Calligraphy Square"], ["Al Fanar Restaurant Sharjah", "Aroos Damascus", "The Arabic Restaurant", "Umm Al Quwain Fish Market", "Fen Café", "Bait Al Rawi", "Paper Fig", "Aroos Al Bahar"], ["Mleiha desert", "Khor Fakkan", "Al Dhaid date farms", "Dubai Creek"], ["Chedi Al Bait", "Al Majaz Premiere Hotel", "72 Hotel", "Sheraton Sharjah Beach Resort", "The Act Hotel", "Occidental Sharjah Grand"], [t("Remember the dry law", "Sharjah is a dry emirate; alcohol is not served in hotels or restaurants.", "etiquette"), t("Cross the border off-peak", "Dubai–Sharjah traffic is heavy at commuting hours.", "transport"), t("Reserve museum slots", "Popular cultural venues and Rain Room can sell out at weekends.", "timing")]),
  singapore: p([2, 4], [4000, 8500, 22000], "Fly into Changi Airport; the MRT is the simplest route into central Singapore.", [a("Chinatown", "Hawker centres, temples and shophouses beside the CBD.", ["food", "history"], "mid"), a("Kampong Glam", "Malay heritage, textile shops and independent cafés.", ["culture", "design"], "mid"), a("Tiong Bahru", "Art Deco flats, bakeries and a celebrated market.", ["food", "walking"], "lux")], [d("Hainanese chicken rice", "Compare poached and roasted versions at a hawker centre.", false), d("Laksa", "Katong-style coconut laksa is a local classic.", false), d("Kaya toast", "Pair the toast and soft egg with kopi for breakfast.", true)], ["Gardens by the Bay", "National Gallery Singapore", "Pulau Ubin cycling", "Hawker centre trail", "Jewel Rain Vortex"], ["Maxwell Food Centre", "Lau Pa Sat", "328 Katong Laksa", "Burnt Ends", "Candlenut", "Tiong Bahru Bakery", "Old Airport Road Food Centre", "The Coconut Club"], ["Sentosa Island", "Johor Bahru", "Southern Ridges", "Pulau Ubin"], ["The Pod Boutique Capsule", "Hotel Mono", "Oasia Hotel Downtown", "The Fullerton Hotel", "The Warehouse Hotel", "Capella Singapore"], [t("Use an EZ-Link or SimplyGo card", "The MRT reaches almost every attraction and fares are distance-based.", "transport"), t("Queue at hawker stalls", "Long queues usually signal a specialist stall; return trays after eating.", "etiquette"), t("Carry a water bottle", "Singapore is hot and humid, while museums and malls are heavily air-conditioned.", "health")]),
  hanoi: p([3, 5], [1800, 4500, 11000], "Fly into Noi Bai International; the airport bus or an app taxi takes about an hour to the Old Quarter.", [a("Old Quarter", "Narrow guild streets, coffee counters and Hoan Kiem walks.", ["food", "walking"], "mid"), a("Ba Dinh", "Tree-lined avenues, the mausoleum and museums.", ["history", "quiet"], "mid"), a("Tay Ho", "Lakeside cafés, international dining and longer stays.", ["cafés", "slow travel"], "lux")], [d("Bún chả", "Eat grilled pork and herbs separately before mixing the noodles.", false), d("Phở bò", "Try an early-morning bowl at a specialist counter.", false), d("Cà phê trứng", "The whipped egg coffee is Hanoi's unmistakable sweet drink.", true)], ["Temple of Literature", "Train Street from a permitted café", "Hoan Kiem early walk", "Water puppet theatre", "Dong Xuan Market"], ["Bún Chả Hương Liên", "Phở Gia Truyền Bát Đàn", "Bánh Cuốn Bà Hoành", "Chả Cá Lã Vọng", "Xôi Yến", "Giảng Cafe", "Tầm Vị", "Bún Ốc Cô Huệ"], ["Ha Long Bay", "Ninh Binh and Trang An", "Perfume Pagoda", "Bat Trang pottery village"], ["Little Charm Hanoi Hostel", "La Siesta Classic Ma May", "Peridot Grand", "Sofitel Legend Metropole", "Apricot Hotel", "InterContinental Hanoi Westlake"], [t("Cross slowly", "Walk at a steady pace and let scooters flow around you rather than stopping mid-road.", "safety"), t("Use metered or app taxis", "Grab helps avoid misunderstandings, especially for airport transfers.", "transport"), t("Protect your phone", "Keep it away from the road edge when photographing busy streets.", "safety")]),
  "da-nang": p([2, 4], [2000, 5000, 12500], "Fly into Da Nang International, a short taxi ride from the riverfront and beach.", [a("My Khe", "Long sandy beach, seafood restaurants and modern hotels.", ["beach", "families"], "mid"), a("Hai Chau", "Central riverfront, markets and local breakfast shops.", ["food", "transport"], "budget"), a("Son Tra", "Peninsula greenery, sea views and resort hideaways.", ["nature", "quiet"], "lux")], [d("Mì Quảng", "The turmeric noodles come with herbs, peanuts and little broth.", false), d("Bún chả cá", "Da Nang's fish-cake noodle soup is a local breakfast staple.", false), d("Bánh xèo", "Wrap the crisp pancake in leaves and dip generously.", false)], ["Marble Mountains caves", "Dragon Bridge weekend fire show", "Son Tra Peninsula", "My Khe sunrise", "Cham Sculpture Museum"], ["Bé Mặn seafood", "Mỳ Quảng Bà Mua", "Bún Chả Cá 109", "Madam Lan", "Bánh Xèo Bà Dưỡng", "Cô Ba", "Le Comptoir", "Namaste Danang"], ["Hoi An Ancient Town", "Ba Na Hills and Golden Bridge", "My Son Sanctuary", "Hue Imperial City"], ["Rom Casa Da Nang", "Hadana Boutique Hotel", "Sala Danang Beach", "InterContinental Danang", "Furama Resort", "TMS Hotel Da Nang"], [t("Use the river as your anchor", "Most central sights sit within an easy ride of the Han River.", "transport"), t("Ride only with a helmet", "App motorbike taxis are convenient; choose a car in heavy rain.", "safety"), t("Visit caves before noon", "Marble Mountains get hot and crowded later in the day.", "timing")]),
  "ho-chi-minh-city": cityProfile([2, 4], [2000, 5200, 14000], "Fly into Tan Son Nhat; app taxis reach District 1 in 20–40 minutes depending on traffic.", ["District 1", "District 3", "Thao Dien"], ["cơm tấm", "bánh xèo", "chè"], ["War Remnants Museum", "Ben Thanh Market", "Saigon River sunset cruise", "Jade Emperor Pagoda", "Nguyen Hue walking street"], ["Cơm Tấm Ba Ghiền", "Bánh Xèo Ngọc Sơn", "Ốc Oanh", "Pho Hoa Pasteur", "Bánh Mì Huynh Hoa", "Cuc Gach Quan", "Quan Ut Ut", "The Refinery"], ["Cu Chi Tunnels", "Mekong Delta", "Tay Ninh and Cao Dai Temple", "Can Gio mangrove"], ["The Dorm Saigon", "Silverland Yen", "Hotel des Arts Saigon", "Park Hyatt Saigon", "The Reverie Saigon", "Villa Song Saigon"], ["Protect your phone", "Use the pedestrian bridges on major roads.", "Use Grab for airport rides"]),
  "hoi-an": p([2, 4], [2200, 5200, 13000], "Fly to Da Nang then take a 45-minute taxi or shuttle to Hoi An.", [a("Ancient Town", "Lantern-lit merchant houses and pedestrian lanes.", ["history", "walking"], "mid"), a("Cam Chau", "Rice paddies, homestays and bicycles close to town.", ["cycling", "quiet"], "budget"), a("An Bang", "A relaxed beach strip with seafood and cafés.", ["beach", "slow travel"], "lux")], [d("Cao lầu", "Look for the chewy noodles, greens and char siu pork.", false), d("White rose dumplings", "These translucent shrimp dumplings are unique to Hoi An.", false), d("Bánh mì", "Try the crispy baguette from a busy local counter.", false)], ["Lantern-making workshop", "Thu Bon River boat at dusk", "My Son Sanctuary", "Tra Que herb village cycle", "Japanese Covered Bridge"], ["Bánh Mì Phượng", "Madam Khanh", "Morning Glory", "Cao Lầu Thanh", "Mót Hội An", "Cargo Club", "Bale Well", "The Fisherman"], ["Da Nang", "Cham Islands", "My Son Sanctuary", "Marble Mountains"], ["Tribee Kinh", "Little Riverside Hoi An", "Almanity Hoi An", "Anantara Hoi An", "Four Seasons The Nam Hai", "Victoria Hoi An"], [t("Buy tailoring with time", "Allow at least two fittings rather than promising same-day collection.", "shopping"), t("Walk after dusk", "The Ancient Town restricts traffic, making evenings especially pleasant.", "timing"), t("Carry a rain layer", "Central Vietnam showers can arrive quickly outside the dry season.", "weather")]),
  tbilisi: q([3, 5], [2200, 5200, 13000], "Fly into Tbilisi International; the airport train and app taxis reach the centre.", ["Sololaki", "Vera", "Avlabari"], ["khinkali", "khachapuri", "churchkhela"], ["Narikala Fortress", "Sulphur baths", "Georgian wine tasting", "Dry Bridge Market", "Rustaveli Avenue"], ["Keto and Kote", "Shavi Lomi", "Puri Guliani", "Barbarestan", "Erekle II Street", "Culinarium Khasheria", "Cafe Littera", "Vino Underground"], ["Mtskheta and Jvari", "Kazbegi", "Kakheti wine region", "Uplistsikhe"], ["Fabrika Tbilisi", "Rooms Hotel Tbilisi", "Stamba Hotel", "Radisson Blu Iveria", "Tbilisi Marriott", "Communal Hotel Sololaki"], ["Use Bolt for taxis", "The app shows the fare and avoids negotiation.", "Try supra dishes gradually"]),
  batumi: q([3, 5], [2200, 5000, 12000], "Fly to Batumi International or take a train from Tbilisi; the station is outside the centre.", ["Old Batumi", "New Boulevard", "Gonio"], ["Adjarian khachapuri", "Borano", "churchkhela"], ["Batumi Boulevard", "Alphabetic Tower", "Adjara wine tasting", "Botanical Garden", "Gonio Fortress"], ["Heart of Batumi", "Laguna", "Retro", "Chacha Time", "Blue Elephant", "Nino's", "Porto Franco", "Old Boulevard"], ["Batumi Botanical Garden", "Mtirala National Park", "Gonio and Sarpi", "Kutaisi"], ["Hostel Batumi", "Hotel Old Town", "Rooms Hotel Batumi", "Hilton Batumi", "Le Méridien Batumi", "Paragraph Resort"], ["Check sea weather", "Black Sea storms can cancel boat plans.", "Carry a light rain shell"]),
  kutaisi: q([2, 4], [1800, 4200, 10000], "Fly into Kutaisi International; marshrutkas and taxis connect the airport with town.", ["White Bridge", "Bagrati", "Tskaltubo"], ["imeruli khachapuri", "lobio", "churchkhela"], ["Bagrati Cathedral", "Kutaisi Green Bazaar", "Prometheus Cave", "Gelati Monastery", "Rioni riverside"], ["Sisters", "Palaty", "Bikentia's Kebabery", "Sapere", "Kutaisi Market", "Destino", "El Depo", "Magnolia"], ["Okatse Canyon", "Martvili Canyon", "Gelati and Motsameta", "Tskaltubo"], ["Hostel Kutaisi", "Hotel Newport", "Best Western Kutaisi", "Aia Hotel", "Kutaisi Inn", "Tskaltubo Plaza"], ["Confirm marshrutka times", "Routes can be less frequent outside morning.", "Wear shoes for cave walks"]),
  baku: q([3, 5], [3000, 7000, 18000], "Fly into Heydar Aliyev Airport; the Aero Express bus reaches 28 May station.", ["Icherisheher", "Nizami Street", "White City"], ["plov", "qutab", "pakhlava"], ["Flame Towers viewpoint", "Old City Maiden Tower", "Heydar Aliyev Center", "Caspian boulevard", "Carpet Museum"], ["Firuze", "Dolma Restaurant", "Şirvanşah", "Mangal Steak House", "Nargiz Restaurant", "Baku Café", "Xurşidbanu Natəvan", "Chinar"], ["Gobustan petroglyphs", "Yanar Dag", "Qobustan mud volcanoes", "Shamakhi"], ["Sahil Hostel", "The Merchant Baku", "Fairmont Baku", "Four Seasons Baku", "JW Marriott Absheron", "Boutique Hotel Seven Rooms"], ["Use the metro card", "Baku's metro is efficient for longer cross-city hops.", "Carry a light layer by the Caspian"]),
  sheki: q([2, 4], [1800, 4000, 9500], "Travel by bus or marshrutka from Baku; the scenic road takes several hours.", ["Sheki old town", "Caravanserai quarter", "Kish"], ["sheki halva", "piti", "dushbara"], ["Sheki Khan's Palace", "Upper Caravanserai", "Kish Albanian church", "Craft workshop", "Sheki bazaar"], ["Shebeke Restaurant", "Gagarin", "Chalabi Khan", "Sheki Halva House", "Ilham's Tea House", "Karvansaray"], ["Lahic village", "Qax waterfalls", "Zagatala", "Kish"], ["Sheki Palace Hotel", "Karvansaray Hotel", "Ilgar's Hostel", "Macara Sheki City Hotel", "Sheki Park", "Marxal Resort"], ["Carry cash", "Small guesthouses and tea houses may not take cards.", "Allow extra road time"]),
  gabala: q([2, 4], [2200, 4800, 11000], "Drive or take a bus from Baku; a private driver is useful for scattered sights.", ["Gabala town", "Tufandag", "Nohur Lake"], ["qabala plov", "kutab", "sheki halva"], ["Tufandag cable car", "Nohur Lake", "Seven Beauties waterfall", "Gabala shooting centre", "Yeddi Gozel forest"], ["RaNa Restaurant", "Çinar", "Qabala Khan", "Duyma", "Nohur Lake Café", "Dost Qapisi"], ["Sheki", "Lahic", "Ismayilli", "Shamakhi"], ["Gabala Garden Hotel", "Qafqaz Riverside", "Qafqaz Tufandag", "Chenot Palace", "White Boutique Hotel", "Qafqaz Thermal"], ["Book mountain rides ahead", "Cable-car weather can change quickly.", "A car saves time between valleys"]),
  kathmandu: q([3, 5], [1800, 4500, 11000], "Fly into Tribhuvan International; pre-paid taxis and app rides reach Thamel.", ["Thamel", "Patan", "Boudha"], ["momo", "dal bhat", "sel roti"], ["Swayambhunath", "Pashupatinath", "Patan Durbar Square", "Boudhanath", "Asan market"], ["Bota Momo", "Thakali Bhanchha", "Roadhouse Cafe", "Krishnarpan", "Yangling Tibetan Restaurant", "OR2K", "New Orleans Cafe", "Kaiser Cafe"], ["Bhaktapur", "Nagarkot", "Chitwan", "Namo Buddha"], ["Alobari Hostel", "Kantipur Temple House", "Hotel Yak and Yeti", "Dwarika's Hotel", "Hyatt Regency Kathmandu", "Hotel Shambala"], ["Use a local guide for temples", "A guide adds context and helps with complex entry areas.", "Carry small rupee notes"]),
  pokhara: q([3, 5], [1800, 4500, 11000], "Fly from Kathmandu to Pokhara or take the long scenic road; taxis serve Lakeside.", ["Lakeside", "Damside", "Sarangkot"], ["thakali set", "momo", "sel roti"], ["Phewa Lake boat", "World Peace Pagoda", "Sarangkot sunrise", "International Mountain Museum", "Begnas Lake cycle"], ["Moondance Restaurant", "Thakali Kitchen", "Caffe Concerto", "Pokhara Thakali Kitchen", "Fresh Elements", "OR2K Pokhara", "Roadhouse Lakeside", "The Juicery"], ["Annapurna Base Camp", "Australian Camp", "Bandipur", "Chitwan"], ["Hotel Middle Path", "Temple Tree Resort", "Bar Peepal Resort", "Fish Tail Lodge", "The Pavilions Himalayas", "Waterfront Resort"], ["Keep a weather buffer", "Mountain flights and views are easily delayed by cloud.", "Use a licensed trekking guide"]),
  chitwan: q([2, 4], [2000, 4800, 12000], "Fly to Bharatpur or travel by tourist bus from Kathmandu or Pokhara; Sauraha is a short transfer.", ["Sauraha", "Bachhauli", "Meghauli"], ["tharu fish", "dal bhat", "sel roti"], ["Chitwan jeep safari", "Tharu cultural dance", "Rapti canoe", "Elephant Breeding Centre", "Community forest walk"], ["Jungle View Restaurant", "KC's Restaurant", "Park's Pub", "Sauraha Thakali Kitchen", "Greasy Spoon", "Friends Cafe", "Royal Kitchen", "Jungle Sunset Camp"], ["Devghat", "Bharatpur", "Bishazari Tal", "Bandipur"], ["Chitwan Gaida Lodge", "Green Park Chitwan", "Barahi Jungle Lodge", "Kasara Resort", "Meghauli Serai", "Tiger Tops Tharu Lodge"], ["Choose jeep safaris", "Responsible operators keep distance and avoid elephant rides.", "Bring binoculars and muted clothes"]),
  colombo: q([2, 4], [2200, 5200, 13000], "Fly into Bandaranaike International; the airport expressway reaches Colombo by taxi or bus.", ["Fort", "Kollupitiya", "Cinnamon Gardens"], ["kottu roti", "hoppers", "pol sambol"], ["Galle Face sunset", "Gangaramaya Temple", "Pettah market", "Colombo National Museum", "Dutch Hospital quarter"], ["Ministry of Crab", "Upali's", "Nuga Gama", "Pettah Kottu King", "The Gallery Cafe", "Paradise Road Tintagel", "Shanmugas", "Kottu Labs"], ["Galle", "Negombo", "Kandy", "Bentota"], ["Clock Inn Colombo", "Fairway Colombo", "Galle Face Hotel", "Cinnamon Grand", "Mövenpick Colombo", "Maniumpathy"], ["Use PickMe", "The local ride app is usually clearer than negotiating tuk-tuk fares.", "Avoid beach swims after rough seas"]),
  kandy: q([2, 4], [2000, 4800, 12000], "Take the train or a private car from Colombo; Kandy station is central.", ["Kandy Lake", "Peradeniya", "Katugastota"], ["kandy milk rice", "hoppers", "watalappam"], ["Temple of the Tooth", "Kandy lake walk", "Esala Perahera museum", "Peradeniya Gardens", "Ceylon tea tasting"], ["Theva Residency", "Balaji Dosai", "Kandy Muslim Hotel", "Royal Bar", "White House Restaurant", "Slightly Chilled Lounge", "Hideout Lounge", "Cafe Secret Garden"], ["Sigiriya", "Dambulla Cave Temple", "Nuwara Eliya", "Knuckles Range"], ["Kandy City Stay", "Thilanka Hotel", "Earl's Regent", "Theva Residency", "Kings Pavilion", "Madulkelle Tea Resort"], ["Book trains early", "Scenic observation seats sell out on the Kandy route.", "Dress conservatively at the Temple"]),
  galle: q([2, 4], [2200, 5400, 14000], "Drive or take the coastal train from Colombo; Galle Fort is walkable from the station.", ["Galle Fort", "Unawatuna", "Dewata"], ["fish ambul thiyal", "kottu roti", "hoppers"], ["Galle Fort ramparts", "Maritime Museum", "Unawatuna snorkel", "Jungle Beach", "Lighthouse sunset"], ["A Minute by Tuk Tuk", "Poonie's Kitchen", "Pedlar's Inn", "Fort Printers", "Chambers", "The Tuna & The Crab", "Indian Hut", "Royal Dutch Cafe"], ["Mirissa", "Hikkaduwa", "Yala National Park", "Weligama"], ["The Fort Bazaar", "Galle Fort Hotel", "Amangalla", "Le Grand Galle", "Radisson Blu Galle", "Kahanda Kanda"], ["Walk the ramparts at dusk", "The stone gets hot in midday sun.", "Check surf conditions before swimming"]),
  ella: q([2, 4], [1800, 4500, 11000], "Take the famous hill-country train from Kandy or Nuwara Eliya; tuk-tuks connect the valley.", ["Ella town", "Kithalella", "Passara"], ["rice and curry", "roti", "watalappam"], ["Nine Arch Bridge", "Little Adam's Peak", "Ella Rock", "Ravana Falls", "Tea factory visit"], ["Matey Hut", "Cafe Chill", "360 Ella", "Ravana Heights", "AK Ristoro", "Ella Spice Garden", "MozzarElla", "Ceylon Tea Factory"], ["Haputale", "Nuwara Eliya", "Udawalawe", "Yala"], ["Hangover Hostels", "Mountain Heavens", "98 Acres Resort", "EKHO Ella", "Ravana Heights", "Madulkelle Tea Resort"], ["Start hikes early", "Cloud builds over the hills by afternoon.", "Keep train plans flexible"]),
  tokyo: q([4, 6], [4500, 10000, 26000], "Fly into Haneda for the quickest city transfer or Narita for wider international connections.", ["Asakusa", "Shibuya", "Kiyosumi-Shirakawa"], ["sushi", "ramen", "monjayaki"], ["Senso-ji at dawn", "Tsukiji outer market", "teamLab Borderless", "Shibuya crossing", "Meiji Jingu"], ["Sushi Dai", "Tsukiji Kiyomura", "Ramen Street", "Tsukemen Yasuda", "Narisawa", "Afuri", "Tonkatsu Maisen", "Uobei Shibuya"], ["Kamakura", "Nikko", "Hakone", "Yokohama"], ["Book and Bed Tokyo", "Hotel Gracery Shinjuku", "MUJI Hotel Ginza", "Park Hyatt Tokyo", "Hoshinoya Tokyo", "The Gate Hotel Kaminarimon"], ["Use an IC card", "Suica or Pasmo makes local trains and convenience-store payments easy.", "Reserve popular counters"]),
  kyoto: q([3, 5], [4000, 9000, 24000], "Take the Haruka train from Kansai Airport or the shinkansen from Tokyo to Kyoto Station.", ["Gion", "Higashiyama", "Arashiyama"], ["kaiseki", "yudofu", "matcha sweets"], ["Fushimi Inari before sunrise", "Kiyomizu-dera", "Nishiki Market", "Arashiyama bamboo grove", "Tea ceremony"], ["Izuju", "Omen", "Kikunoi", "Nishiki Warai", "Gion Sasaki", "Yoshikawa Tempura", "Men-ya Inoichi", "Saryo Tsujiri"], ["Nara", "Uji", "Ohara", "Himeji"], ["Piece Hostel Sanjo", "The Gate Hotel Kyoto", "Sowaka", "Ace Hotel Kyoto", "Tawaraya", "Ritz-Carlton Kyoto"], ["Respect residential lanes", "Do not photograph geiko or private entrances.", "Book temple slots early"]),
  osaka: q([3, 5], [3500, 8000, 20000], "Kansai International Airport connects by Nankai or JR train; Shin-Osaka serves shinkansen.", ["Namba", "Umeda", "Nakazakicho"], ["takoyaki", "okonomiyaki", "kitsune udon"], ["Dotonbori food walk", "Osaka Castle", "Kuromon Market", "Umeda Sky Building", "Shinsekai"], ["Mizuno", "Kushikatsu Daruma", "Harijyu", "Endo Sushi", "Ajinoya", "Takoyaki Wanaka", "Kani Doraku", "Tsurutontan"], ["Nara", "Himeji Castle", "Kobe", "Minoh Park"], ["Hotel The Flag", "The Lively Osaka", "Cross Hotel Osaka", "Conrad Osaka", "Swissotel Nankai", "Zentis Osaka"], ["Eat before peak queues", "Small counters often have a simple ticket machine.", "Use Osaka Metro day passes selectively"]),
  sapporo: q([3, 5], [3500, 8000, 19000], "Fly into New Chitose; the rapid airport train reaches Sapporo in about 40 minutes.", ["Odori", "Susukino", "Maruyama"], ["miso ramen", "jingisukan", "soup curry"], ["Odori Park", "Sapporo Beer Museum", "Nijo Market", "Mt Moiwa night view", "Snow Festival sites"], ["Sapporo Ramen Shingen", "Daruma", "Nemuro Hanamaru", "Suage+", "Sapporo Beer Garden", "Kani Honke", "Sato Suisan", "Ebisoba Ichigen"], ["Otaru", "Noboribetsu", "Furano and Biei", "Jozankei"], ["The Stay Sapporo", "Hotel MYSTAYS", "Cross Hotel Sapporo", "JR Tower Hotel Nikko", "ANA Crowne Plaza", "Lake Shikotsu Tsuruga"], ["Reserve winter trains", "Snow and weather can disrupt regional services.", "Bring proper layers for exposed viewpoints"]),
  "kuala-lumpur": q([2, 4], [2200, 5200, 14000], "KLIA Ekspres reaches KL Sentral in 28 minutes; app taxis are useful for outer neighbourhoods.", ["Bukit Bintang", "Brickfields", "Kampung Baru"], ["nasi lemak", "roti canai", "char kway teow"], ["Petronas Twin Towers", "Jalan Alor night food", "Islamic Arts Museum", "Batu Caves", "Merdeka Square"], ["Village Park Nasi Lemak", "Bijan", "Lot 10 Hutong", "Restoran Yut Kee", "Nasi Kandar Pelita", "Merchant's Lane", "Limapulo", "Fierce Curry House"], ["Putrajaya", "Batu Caves", "Malacca", "Genting Highlands"], ["BackHome KL", "Else Kuala Lumpur", "Majestic Hotel", "Banyan Tree KL", "Mandarin Oriental", "The RuMa"], ["Use Touch 'n Go", "Rail is fastest across the centre; avoid driving at rush hour.", "Dress lightly but carry a mosque cover-up"]),
  langkawi: q([3, 5], [2500, 6000, 16000], "Fly into Langkawi International; pre-book a taxi or rent a car for the island.", ["Pantai Cenang", "Kuah", "Tanjung Rhu"], ["nasi dagang", "laksa kedah", "pulut mangga"], ["Langkawi SkyCab", "Kilim Geoforest mangroves", "Pantai Cenang sunset", "Eagle Square", "Island-hopping boat"], ["The Cliff Langkawi", "Orkid Ria Seafood", "Yellow Beach Cafe", "Nasi Dagang Pak Malau", "Fat Cupid", "The Gulai House", "Haroo+", "Scarborough Fish"], ["Koh Lipe", "Dayang Bunting Island", "Pulau Payar Marine Park", "Kilim"], ["Bed Attitude", "Aloft Langkawi", "Casa del Mar", "The Datai", "Four Seasons Langkawi", "The Ritz-Carlton Langkawi"], ["Rent only if insured", "Roads are easy but wildlife and unlit stretches need care.", "Check boat weather before island trips"]),
  penang: q([2, 4], [2000, 5000, 13000], "Fly into Penang International or take the train to Butterworth and ferry across.", ["George Town", "Jelutong", "Tanjung Bungah"], ["char kway teow", "asam laksa", "hokkien mee"], ["George Town street art", "Khoo Kongsi", "Penang Hill", "Clan Jetties", "Blue Mansion"], ["Tek Sen", "Siam Road Char Kway Teow", "Air Itam Laksa", "Gurney Drive Hawker Centre", "Kebaya", "ChinaHouse", "Joo Hooi Cafe", "Deen Maju"], ["Kek Lok Si", "Balik Pulau", "Butterworth", "Taiping"], ["The Frame Guesthouse", "Cheong Fatt Tze", "Campbell House", "Eastern & Oriental", "The Edison George Town", "Macalister Mansion"], ["Go hungry to hawker centres", "Portions are small enough to graze across several stalls.", "Use buses for Penang Hill"]),
  malacca: q([2, 4], [1800, 4500, 11000], "Buses from Kuala Lumpur arrive at Melaka Sentral; taxis or Grab reach the heritage core.", ["Jonker Walk", "Heeren Street", "Portuguese Settlement"], ["chicken rice balls", "nyonya laksa", "cendol"], ["A Famosa", "Jonker Walk night market", "Melaka river cruise", "Baba Nyonya Museum", "Stadthuys"], ["Kedai Kopi Chung Wah", "Nancy's Kitchen", "Jonker 88", "The Daily Fix", "Pak Putra", "Restoran Nyonya Makko", "Capitol Satay", "Geographer Cafe"], ["Kuala Lumpur", "Muar", "Tanjung Bidara", "Port Dickson"], ["The Nest House", "Rosa Malacca", "Casa del Rio", "The Majestic Malacca", "Puri Melaka", "Baba House"], ["Visit Jonker early", "Crowds build after sunset on Friday and Saturday.", "Use a riverside walk to orient yourself"]),
  istanbul: q([3, 5], [3200, 7500, 19000], "Istanbul Airport and Sabiha Gökçen have metro, shuttle and taxi links; choose by your neighbourhood.", ["Sultanahmet", "Karaköy", "Kadıköy"], ["simit", "ıslak burger", "baklava"], ["Hagia Sophia and Blue Mosque", "Bosphorus ferry", "Grand Bazaar", "Topkapı Palace", "Galata Tower"], ["Karaköy Lokantası", "Çiya Sofrası", "Pandeli", "Karaköy Güllüoğlu", "Dönerci Şahin Usta", "Balkan Lokantası", "Mikla", "Namlı Gurme"], ["Bursa", "Princes' Islands", "Şile", "Edirne"], ["Cheers Hostel", "The Stay Bosphorus", "Pera Palace", "Four Seasons Sultanahmet", "The House Hotel Karakoy", "Raffles Istanbul"], ["Use ferries as transport", "They are scenic, frequent and avoid bridge traffic.", "Check mosque prayer closures"]),
  cappadocia: q([2, 4], [4000, 9000, 23000], "Fly to Kayseri or Nevşehir; hotel transfers are the simplest way to reach Göreme.", ["Göreme", "Uçhisar", "Avanos"], ["testi kebab", "manti", "gözleme"], ["Hot-air balloon flight", "Göreme Open Air Museum", "Rose Valley hike", "Underground city", "Avanos pottery"], ["Seten Restaurant", "Dibek", "Topdeck Cave", "Ziggy Cafe", "Seki Restaurant", "Old Cappadocia Cafe", "Pumpkin Goreme", "Millocal"], ["Derinkuyu", "Ihlara Valley", "Zelve and Paşabağ", "Kayseri"], ["Kose Pension", "Mithra Cave Hotel", "Argos in Cappadocia", "Museum Hotel", "Aza Cave Hotel", "Cappadocia Cave Suites"], ["Book balloons early", "Flights are weather-dependent and fill in high season.", "Wear grippy shoes for valleys"]),
  antalya: q([3, 5], [2800, 6500, 17000], "Fly into Antalya Airport; the tram reaches the city and taxis serve resorts.", ["Kaleiçi", "Konyaaltı", "Lara"], ["piyaz", "serpme börek", "kabak tatlısı"], ["Kaleiçi harbour", "Düden Waterfalls", "Antalya Museum", "Konyaaltı beach", "Aspendos theatre"], ["7 Mehmet", "Piyazcı Sami", "Seraser", "Lara Balık", "Kaleiçi Meyhanesi", "Rokka", "Ayar Meyhanesi", "Vanilla"], ["Perge and Aspendos", "Termessos", "Side", "Olympos and Çıralı"], ["Kosa Boutique", "Akra Hotel", "Tuvana Hotel", "Rixos Downtown", "Titanic Mardan Palace", "D Maris Bay"], ["Keep a beach buffer", "Ruins and waterfalls are spread along the coast.", "Use shade at midday in summer"]),
  izmir: q([2, 4], [2500, 5800, 14500], "Fly into Adnan Menderes; İZBAN trains connect the airport with central İzmir.", ["Konak", "Alsancak", "Kemeraltı"], ["boyoz", "kumru", "şambali"], ["Kordon promenade", "Kemeraltı Bazaar", "Agora of Smyrna", "Asansör", "İzmir Archaeology Museum"], ["Deniz Restaurant", "Topçu", "Hisarönü Şambalicisi", "Köfteci Salih", "Tavacı Recep Usta", "Seçkin Et", "Yengeç Restaurant", "Kordon Yengeç"], ["Ephesus", "Şirince", "Çeşme", "Pergamon"], ["Lotus Garden Hostel", "Key Hotel", "Mövenpick Izmir", "Swissôtel Büyük Efes", "İzmir Marriott", "Svalinn Hotel"], ["Take the train to Selçuk", "It is straightforward and avoids Aegean summer traffic.", "Carry a hat for Ephesus"]),
} satisfies Record<string, CityProfile>;

// Source-backed corrections from the September 2026 launch review.
(cityProfiles.bangkok as CityProfile).gettingIn = "Fly into Suvarnabhumi or Don Mueang; the Airport Rail Link runs from Suvarnabhumi, while Don Mueang is served by the SRT Red Line.";
(cityProfiles.bangkok as CityProfile).restaurants[1] = "Sorn";
(cityProfiles["abu-dhabi"] as CityProfile).gettingIn = "Fly into Zayed International Airport; the airport bus and taxis reach the island.";
(cityProfiles.singapore as CityProfile).tips[0] = t("Use a SimplyGo EZ-Link or contactless bank card", "The MRT reaches almost every attraction and fares are distance-based.", "transport");
(cityProfiles.ella as CityProfile).gettingIn = "Take the famous hill-country train from Kandy or Nanu Oya (for Nuwara Eliya); tuk-tuks connect the valley.";
(cityProfiles["kuala-lumpur"] as CityProfile).restaurants[0] = "Village Park Nasi Lemak (Petaling Jaya)";
(cityProfiles["kuala-lumpur"] as CityProfile).dayTrips = ["Putrajaya", "Malacca", "Genting Highlands", "Kuala Selangor"];
(cityProfiles.langkawi as CityProfile).dayTrips[3] = "Tanjung Rhu";
(cityProfiles.antalya as CityProfile).stays[5] = "Lara Barut Collection";
(cityProfiles.lombok as CityProfile).stays[2] = "Jati Kuta Lombok";
(cityProfiles["abu-dhabi"] as CityProfile).stays[5] = "The St. Regis Abu Dhabi";
(cityProfiles.sharjah as CityProfile).restaurants[3] = "Mahrosah Restaurant & Sweet Shop";
(cityProfiles.chitwan as CityProfile).restaurants[7] = "Chitwan Tiger Camp Restaurant";
(cityProfiles.kandy as CityProfile).restaurants[0] = "Kandy Crown";
(cityProfiles.ella as CityProfile).restaurants[3] = "The Barn by Starbeans";
(cityProfiles.ella as CityProfile).stays[5] = "Hotel Onrock";
(cityProfiles.tbilisi as CityProfile).restaurants[4] = "Lolita";
(cityProfiles.kutaisi as CityProfile).restaurants[4] = "Gala";