// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/FirstLightCyclingLookbook-AHLALo/ClikClakDuskMix.tsx": () => import("../components/mockups/templates/FirstLightCyclingLookbook-AHLALo/ClikClakDuskMix.tsx"),
  "./components/mockups/templates/FirstLightCyclingLookbook-SGttAx/ClikClakDuskMix.tsx": () => import("../components/mockups/templates/FirstLightCyclingLookbook-SGttAx/ClikClakDuskMix.tsx"),
  "./components/mockups/templates/FirstLightCyclingLookbook-_lkRrh/ClikClakDuskMix.tsx": () => import("../components/mockups/templates/FirstLightCyclingLookbook-_lkRrh/ClikClakDuskMix.tsx")
};
